# Generated by Django 5.0.9 on 2026-09-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respondents', '0002_initial'),
        ('responses', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='respondents.respondent'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveyversion'),
        ),
        migrations.AddField(
            model_name='responsereview',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='responses.surveyresponse'),
        ),
        migrations.AddField(
            model_name='responseflag',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='responses.surveyresponse'),
        ),
        migrations.AddField(
            model_name='responseattachment',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='responses.surveyresponse'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typed_answers', to='responses.surveyresponse'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'status', 'submitted_at'], name='responses_s_survey__21e2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['collected_by_id', 'submitted_at'], name='responses_s_collect_5d438d_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref_id__isnull', False)), fields=('client_ref_id',), name='uniq_response_client_ref_id'),
        ),
        migrations.AddConstraint(
            model_name='responseattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref_id__isnull', False)), fields=('client_ref_id',), name='uniq_attachment_client_ref_id'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question_code', 'value_text'], name='responses_a_questio_3b9a40_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question_code', 'value_number'], name='responses_a_questio_de0af5_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question_code', 'value_date'], name='responses_a_questio_90e645_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question_code', 'repeat_path', 'repeat_index'), name='uniq_answer_per_question_and_repeat_instance'),
        ),
    ]
