# Generated by Django 5.0.9 on 2026-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.DeleteModel(
            name='ResponseReview',
        ),
    ]
