# Generated by Django 5.0.9 on 2026-09-11 11:01

import apps.surveys.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(max_length=100)),
                ('attributes', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=63)),
                ('order', models.PositiveIntegerField()),
                ('title', models.JSONField(default=dict)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('relevant', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'survey categories',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('schema_hash', models.CharField(blank=True, max_length=64)),
                ('change_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('response_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('label', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('choice_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.choicelist')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=63, validators=[apps.surveys.models.validate_question_code])),
                ('type', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('label', models.JSONField(default=dict)),
                ('hint', models.JSONField(blank=True, default=dict)),
                ('is_required', models.CharField(blank=True, default='false', max_length=1000)),
                ('relevant', models.CharField(blank=True, max_length=1000)),
                ('constraint', models.CharField(blank=True, max_length=1000)),
                ('constraint_message', models.JSONField(blank=True, default=dict)),
                ('default_value', models.CharField(blank=True, max_length=1000)),
                ('calculation', models.CharField(blank=True, max_length=1000)),
                ('read_only', models.BooleanField(default=False)),
                ('is_pii', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('choice_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='surveys.choicelist')),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeat_children', to='surveys.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
