# Generated by Django 5.0.9 on 2026-09-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='surveys.surveycategory'),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='published_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyversion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='surveys.surveyversion'),
        ),
        migrations.AddField(
            model_name='survey',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='surveys.surveyversion'),
        ),
        migrations.AddField(
            model_name='section',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.surveyversion'),
        ),
        migrations.AddField(
            model_name='choicelist',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_lists', to='surveys.surveyversion'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('choice_list', 'value'), name='uniq_choice_value_per_list'),
        ),
        migrations.AddConstraint(
            model_name='surveyversion',
            constraint=models.UniqueConstraint(fields=('survey', 'version_number'), name='uniq_survey_version_number'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='uniq_section_code_per_version'),
        ),
        migrations.AddConstraint(
            model_name='choicelist',
            constraint=models.UniqueConstraint(fields=('version', 'name'), name='uniq_choice_list_name_per_version'),
        ),
    ]
