# Generated by Django 5.0.9 on 2026-09-26 08:37

import apps.surveys.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDemographicField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=63, validators=[apps.surveys.models.validate_question_code])),
                ('type', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('label', models.JSONField(default=dict)),
                ('hint', models.JSONField(blank=True, default=dict)),
                ('is_required', models.CharField(blank=True, default='false', max_length=1000)),
                ('is_pii', models.BooleanField(default=False)),
                ('constraint', models.CharField(blank=True, max_length=1000)),
                ('constraint_message', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('choice_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demographic_fields', to='surveys.choicelist')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_fields', to='surveys.surveyversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
