# Generated by Django 5.0.9 on 2026-09-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyassignment',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveyassignment',
            name='assignee_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='assignments.team'),
        ),
        migrations.AddIndex(
            model_name='surveyassignment',
            index=models.Index(fields=['survey', 'status'], name='assignments_survey__4da19d_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assignee_type', 'user'), ('status', 'active')), fields=('survey', 'assignee_user_id'), name='uniq_active_user_assignment_per_survey'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user_id'), name='uniq_team_member'),
        ),
    ]
