# Generated by Django 5.0.9 on 2026-09-11 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('verbal_confirmed', 'Verbal, confirmed'), ('signature', 'Signature'), ('checkbox', 'Checkbox'), ('uploaded_form', 'Uploaded form')], max_length=20)),
                ('granted_at', models.DateTimeField()),
                ('captured_by_id', models.UUIDField(blank=True, null=True)),
                ('captured_offline', models.BooleanField(default=False)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('purposes', models.JSONField(blank=True, default=list)),
                ('signature_attachment_id', models.UUIDField(blank=True, null=True)),
                ('integrity_hash', models.CharField(blank=True, max_length=64)),
                ('client_ref_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('alt_phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('geography_node_id', models.UUIDField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('consent_status', models.CharField(choices=[('none', 'None'), ('granted', 'Granted'), ('withdrawn', 'Withdrawn')], default='none', max_length=20)),
                ('is_anonymised', models.BooleanField(default=False)),
                ('anonymised_at', models.DateTimeField(blank=True, null=True)),
                ('client_ref_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='consentnotice',
            constraint=models.UniqueConstraint(fields=('version', 'language'), name='uniq_notice_version_language'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='respondents.consentnotice'),
        ),
    ]
