# Generated by Django 5.0.9 on 2026-09-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respondents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respondent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respondent',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='respondents.respondent'),
        ),
        migrations.AddIndex(
            model_name='respondent',
            index=models.Index(fields=['phone'], name='respondents_phone_ac4b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='respondent',
            index=models.Index(fields=['identity_number'], name='respondents_identit_26cee4_idx'),
        ),
        migrations.AddConstraint(
            model_name='respondent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('phone__gt', '')), fields=('phone',), name='uniq_respondent_phone'),
        ),
        migrations.AddConstraint(
            model_name='respondent',
            constraint=models.UniqueConstraint(condition=models.Q(('identity_number__gt', ''), ('is_deleted', False)), fields=('identity_number',), name='uniq_respondent_identity_number'),
        ),
        migrations.AddConstraint(
            model_name='respondent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref_id__isnull', False)), fields=('client_ref_id',), name='uniq_respondent_client_ref_id'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref_id__isnull', False)), fields=('client_ref_id',), name='uniq_consent_client_ref_id'),
        ),
    ]
