# Generated by Django 5.0.9 on 2026-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0004_seed_default_demographic_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentrecord',
            name='signature_attachment_id',
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='consent_signatures/%Y/%m/'),
        ),
    ]
