# Generated by Django 5.0.9 on 2026-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0005_remove_consentrecord_signature_attachment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentnotice',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='consent_notices/%Y/%m/'),
        ),
    ]
