# Generated by Django 5.0.9 on 2026-09-18 06:29

import apps.surveys.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# `category` used to point at `surveys.SurveyCategory`. Existing values are
# meaningless against the new, independent `QuestionBankCategory` table, so
# they're cleared before the FK target changes (avoids a constraint failure
# on any existing row) and any question that had one gets refiled under a
# fresh "Farming" bank category afterward -- the only category in use so far.
_cleared_question_ids: list = []


def _capture_and_clear_categories(apps, schema_editor):
    BankQuestion = apps.get_model("question_bank", "BankQuestion")
    ids = list(BankQuestion.objects.filter(category__isnull=False).values_list("id", flat=True))
    _cleared_question_ids[:] = ids
    BankQuestion.objects.filter(id__in=ids).update(category=None)


def _refile_under_farming(apps, schema_editor):
    if not _cleared_question_ids:
        return
    BankQuestion = apps.get_model("question_bank", "BankQuestion")
    QuestionBankCategory = apps.get_model("question_bank", "QuestionBankCategory")
    farming, _ = QuestionBankCategory.objects.get_or_create(name="Farming")
    BankQuestion.objects.filter(id__in=_cleared_question_ids).update(category=farming)


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Kept last: the model's Meta.ordering already refers to
        # `category__name`, but `category` doesn't point at a model with a
        # `name` field until the AlterField below runs -- applying this
        # first would make the RunPython steps' default-ordered queries
        # fail against the still-old FK target.
        migrations.AlterField(
            model_name='bankquestion',
            name='code',
            field=models.CharField(max_length=63, unique=True, validators=[apps.surveys.models.validate_question_code]),
        ),
        migrations.CreateModel(
            name='QuestionBankCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(_capture_and_clear_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bankquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='question_bank.questionbankcategory'),
        ),
        migrations.RunPython(_refile_under_farming, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='bankquestion',
            options={'ordering': ['category__name', 'code']},
        ),
    ]
